### ISSUE TITLE
Crashes with `--load-config presets/verbose`

### ISSUE THREAD

**Issue by CarterLi** [LinusDierheimer/fastfetch#252]
```shell
$ ninja && ./fastfetch --hide-cursor false --show-errors true --disable-linewrap false --load-config ../presets/verbose --recache --multithreading false
ninja: no work to do.
                     c.'          carter@litongzhoudeMacBook-Pro.local
                 ,xNMM.           ------------------------------------
               .OMMMMo            OS: System: Darwin; Name: macOS; Pretty name: macOS; ID: macos; ID like: ; Variant: ; Variant ID: ; Version: 12.6; Version ID: 12.6; Version codename: Monterey; Build ID: 21G115; Architecture: arm64
     .;loddo:.  .olloddol;.       Host: Family: product_family: ; product_name: MacBookPro18,1; product_version: ; product_sku: ; bios_date: ; bios_release: ; bios_vendor: ; bios_version: ; board_name: ; board_vendor: ; board_version: ; chassis_type: ; chassis_vendor: ; chassis_version: ; sys_vendor:
 XMMMMMMMMMMMMMMMMMMMMMMMX.       Kernel: Sysname: Darwin; Release: 21.6.0; Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
:MMMMMMMMMMMMMMMMMMMMMMMM:        Uptime: Days: 0; Hours: 6; Minutes: 8; Seconds: 15
.MMMMMMMMMMMMMMMMMMMMMMMMX.       Packages: All: 244; pacman: 0; pacman branch: ; dpkg: 0; rpm: 0; emerge: 0; xbps: 0; apk: 0; flatpak: 0; snap: 0; brew: 0
 'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Shell: Process name: fish; Process path: /opt/homebrew/bin/fish; Process exe: fish; Process version: 3.5.1; User path: /opt/homebrew/bin/fish; User exe: fish; User version: 3.5.1
    kMMMMMMMMMMMMMMMMMMMMMMd      Resolution: Width: 1728; Height: 1117; Refresh rate: 120
     ;KMMMMMMMWXXWMMMMMMMk.       DE: Process name: aqua; Pretty name: Aqua; Version:
       "cooc*"    "*coo'"         WM: Process name: quartz; Pretty name: Quartz Compositor; Protocol:
                                  WM Theme: Name: Multicolor (Dark)
                                  Theme: No themes found
                                  Icons: No icons could be found
                                  Font: No fonts found
                                  Cursor: Couldn't detect GTK Cursor
                                  Terminal: Process: iTerm.app; Path: iTerm.app; Exe: iTerm.app
=================================================================
==30550==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x00016b8b22a0 at pc 0x00010456fc34 bp 0x00016b8b1ee0 sp 0x00016b8b1ed8
READ of size 4 at 0x00016b8b22a0 thread T0
    #0 0x10456fc30 in ffFormatAppendFormatArg+0xb4 (fastfetch:arm64+0x100023c30)
    #1 0x104572818 in appendEmptyPlaceholder+0x168 (fastfetch:arm64+0x100026818)
    #2 0x1045712f4 in ffParseFormatString+0x7a8 (fastfetch:arm64+0x1000252f4)
    #3 0x104564748 in ffPrintFormatString+0xf8 (fastfetch:arm64+0x100018748)
    #4 0x104564944 in ffPrintFormat+0xb8 (fastfetch:arm64+0x100018944)
    #5 0x1045a6740 in ffPrintTerminalFont+0x90c (fastfetch:arm64+0x10005a740)
    #6 0x1045c2544 in parseStructureCommand+0x4a4 (fastfetch:arm64+0x100076544)
    #7 0x1045c15b8 in main+0x520 (fastfetch:arm64+0x1000755b8)
    #8 0x104ab1088 in start+0x204 (dyld:arm64e+0x5088)

Address 0x00016b8b22a0 is located in stack of thread T0 at offset 96 in frame
    #0 0x1045a5e40 in ffPrintTerminalFont+0xc (fastfetch:arm64+0x100059e40)

  This frame has 1 object(s):
    [32, 96) '.compoundliteral' <== Memory access at offset 96 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (fastfetch:arm64+0x100023c30) in ffFormatAppendFormatArg+0xb4
Shadow bytes around the buggy address:
  0x00702d736400: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702d736410: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x00702d736420: 00 00 f3 f3 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702d736430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702d736440: 00 00 00 00 00 00 00 00 f1 f1 f1 f1 00 00 00 00
=>0x00702d736450: 00 00 00 00[f3]f3 f3 f3 00 00 00 00 00 00 00 00
  0x00702d736460: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702d736470: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x00702d736480: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702d736490: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x00702d7364a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==30550==ABORTING
fish: Job 1, './fastfetch --hide-cursor false…' terminated by signal SIGABRT (Abort)
```

It was strange that breakpoints didn't work on my mac ( it seemed that generated binary didn't contain source file info even in Debug mode ), I always had to use `printf`

**Comment by LinusDierheimer** [comment]
Fixed.
