### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by RayJW** [LinusDierheimer/fastfetch#467]
# General description of bug:

I get a core dump halfway through fastfetch running.

# Often helpful questions:
* Does the issue occur across multiple terminal emulators?
* Yes
* Does the issue occur across multiple shells? (bash, zsh, fish, etc)
* Yes

Output of `fastfetch --version`:
```
fastfetch 1.11.2 (x86_64)
```

Output of `fastfetch --load-config devinfo`:
```
             /////////////                 jeffreyw@desktop-pop
         /////////////////////             --------------------
      ///////*767////////////////          OS: Pop!_OS 22.04 x86_64
    //////7676767676*//////////////        Host: neither product_family nor product_name is set by O.E.M.
   /////76767//7676767//////////////       Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////      Uptime: 5 mins
 ///////767676///76767.///7676*///////     Packages: 3215 (dpkg), 168 (flatpak-user), 9 (snap)
/////////767676//76767///767676////////    Shell: zsh 5.8.1
//////////76767676767////76767/////////    Display 1: 2560x1080 @ 200Hz
///////////76767676//////7676//////////    Display 2: 1920x1080 @ 60Hz
////////////,7676,///////767///////////    DE: Gnome 42.5
/////////////*7676///////76////////////    WM: Mutter (X11)
[1]    24850 segmentation fault (core dumped)  fastfetch --load-config devinfo
```

Output of `fastfetch --load-config devinfo-verbose`:
```
             /////////////                 jeffreyw@desktop-pop
         /////////////////////             --------------------
      ///////*767////////////////          OS: System: Linux; Name: Pop!_OS; Pretty name: Pop!_OS 22.04 LTS; ID: pop; ID like: ubuntu debian; Variant: ; Variant ID: ; Version: 22.04 LTS; Version ID: 22.04; Version codename: jammy; Build ID: ; Architecture: x86_64
    //////7676767676*//////////////        Host: neither product_family nor product_name is set by O.E.M.
   /////76767//7676767//////////////       Bios: 5.17
  /////767676///*76767///////////////      Board: [Irrelevant]
 ///////767676///76767.///7676*///////     Chassis: 3
/////////767676//76767///767676////////    Kernel: Sysname: Linux; Release: 6.2.6-76060206-generic; Version: #202303130630~1685473338~22.04~995127e SMP PREEMPT_DYNAMIC Tue M
//////////76767676767////76767/////////    Uptime: Days: 0; Hours: 0; Minutes: 6; Seconds: 15
///////////76767676//////7676//////////    Processes: Count: 2048
////////////,7676,///////767///////////    Packages: All: 3392; pacman: 0; pacman branch: ; dpkg: 3215; rpm: 0; emerge: 0; eopkg: 0; xbps: 0; apk: 0; flatpak-system: 0; flatpak-user: 0; snap: 0; brew: 0; brew-cask: 0; port: 168; scoop: 9; choco: 0
/////////////*7676///////76////////////    Shell: Process name: zsh; Process path: /bin/zsh; Process exe: zsh; Process version: 5.8.1; User path: /bin/zsh; User exe: zsh; User version: 5.8.1
///////////////7676////////////////////    Display 1: Width: 2560; Height: 1080; Refresh rate: 199.69; ScaledWith: 2560; ScaledHeight: 1080
 ///////////////7676///767////////////     Display 2: Width: 1920; Height: 1080; Refresh rate: 60; ScaledWith: 1920; ScaledHeight: 1080
  //////////////////////'////////////      Brightness: No result is detected.
   //////.7676767676767676767,//////       DE: Process name: gnome-shell; Pretty name: Gnome; Version: 42.5
    /////767676767676767676767/////        WM: Process name: GNOME Shell; Pretty name: Mutter; Protocol: X11
[1]    25111 segmentation fault (core dumped)  fastfetch --load-config devinfo-verbose
```

Output of `fastfetch --list-features`:
```
threads
libpci
vulkan
wayland
xcb-randr
xcb
xrandr
x11
gio
dconf
dbus
imagemagick6
zlib
xfconf
sqlite3
rpm
egl
glx
osmesa
opencl
libpulse
libnm
```

I had the same bug with version 1.11.1, but I thought it might go away with the new version because of some commit I saw, so I thought I'd wait.

**Comment by CarterLi** [comment]
Did you use the default config?

**Comment by RayJW** [comment]
Shouldn't devinfo-verbose and devinfo be default? But to answer your question, yes, I don't even have a custom config file.

**Comment by CarterLi** [comment]
Should be in wmtheme. Can you upload the core dump file?

**Comment by RayJW** [comment]
It is too big to attach here, so I uploaded it: https://send.vis.ee/download/9ab6e259e9becb7d/#VY38dlub0-1zT7ktgg3vUw

**Comment by CarterLi** [comment]
![image](https://github.com/LinusDierheimer/fastfetch/assets/6134068/5d9be2c2-7411-4107-9eaf-d361c18c6e7e)

That, unfortunately, didn't help. Do you know how to use gdb / lldb to get the stack trace?

**Comment by RayJW** [comment]
Well, I have some experience with gdb from reverse engineering, but I wouldn't know how to go about it exactly. Do you maybe have some guide or something? Then I'll gladly try to help.

**Comment by CarterLi** [comment]
```
$ gdb /path/to/fastfetch
* run
* (Wait for it crashing)
* bt
```

**Comment by RayJW** [comment]
```
Reading symbols from /usr/bin/fastfetch...
(No debugging symbols found in /usr/bin/fastfetch)
(gdb) run
Starting program: /usr/bin/fastfetch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7bff640 (LWP 28964)]
[New Thread 0x7fffef3fe640 (LWP 28965)]
[New Thread 0x7ffff73fe640 (LWP 28966)]
[New Thread 0x7ffff6bfd640 (LWP 28967)]
[New Thread 0x7ffff63fc640 (LWP 28968)]
             /////////////                 jeffreyw@desktop-pop
         /////////////////////             --------------------
      ///////*767////////////////          OS: Pop!_OS 22.04 x86_64
    //////7676767676*//////////////        Kernel: 6.2.6-76060206-generic
   /////76767//7676767//////////////       Uptime: 22 mins
[Detaching after vfork from child process 28970]
 ///////767676///76767.///7676*///////     Packages: 3224 (dpkg), 168 (flatpak-user), 9 (snap)
[Detaching after fork from child process 28972]
[Detaching after fork from child process 28973]
[Thread 0x7fffef3fe640 (LWP 28965) exited] 
[Thread 0x7ffff7bff640 (LWP 28964) exited] 
[New Thread 0x7fffef3fe640 (LWP 28974)]    
[New Thread 0x7ffff7bff640 (LWP 28975)]    
[Thread 0x7ffff73fe640 (LWP 28966) exited]
[Thread 0x7ffff63fc640 (LWP 28968) exited]
[Thread 0x7ffff6bfd640 (LWP 28967) exited]
    /////767676767676767676767/////        Shell: zsh 5.8.1
      ///////////////////////////          Display 1: 2560x1080 @ 200Hz
         /////////////////////             Display 2: 1920x1080 @ 60Hz
             /////////////                 DE: Gnome 42.5
                                           WM: Mutter (X11)
[New Thread 0x7ffff63fc640 (LWP 28976)]

Thread 1 "fastfetch" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00005555555821c7 in getGVariantValue ()
#2  0x000055555556ccf0 in ffPrintWMTheme ()
#3  0x000055555558ba65 in parseStructureCommand ()
#4  0x000055555555c9f0 in main ()
```

This is the output from the crash and the stack trace.

**Comment by CarterLi** [comment]
Thanks for reporting
